### ISSUE TITLE
Chromosome size

### ISSUE THREAD

**Issue by walleyResearch** [dblhlx/PyBSASeq#13]
My reference genome still has a lot of smaller contigs. We will make a new HI-C assembly and linkage map later in the year.
In my first run I used the defaults (default='2000000,10000') and chrs smaller than 2510000 bp were not included/ not suitable for analyses, can you recommend the smallest window and increment that will be useable for a deeper scan and not return an invalid lambda error?  
Thank you.

**Comment by dblhlx** [comment]
Sorry for the late reply. GitHub somehow sends me notifications only for issue replies, not for new issues.

Small contigs are chromosomal segments whose positions in the genome are unknown. If such a contig contains a trait-controlling gene, SNPs/InDels in this contig and the chromosomal fragments flanking it will be enriched. It is very likely that the positions of the flanking chromosomal fragments are known. So we can still obtain the mapping information of this trait-controlling gene. 

The purpose of using sliding windows is to get rid of some noises in the BSA-Seq plot. Large window sizes lead to smoother plots. I have not played too much with sliding window sizes and increments. The smallest windows I haves used  so far are 1000000 in rice and 5000000 in maize. The large the genome, the large the sliding windows. What is the genome size of the organism you are working with?

An invalid lambda error should be caused by a bug. Would you please include more details of the error here?

**Comment by walleyResearch** [comment]
Thanks for the reply.  I will re-run the analyses and post the output here.
